### ISSUE TITLE
Social media Share buttons' behavior needs work

### ISSUE THREAD

**Issue by nathanhourt** [BitShares/web_services#18]
From https://bitsharestalk.org/index.php?topic=14323.msg186738#msg186738:

> Yes, after registering an account there is the option to share the new account name on facebook or twitter from the faucet website.   On clicking through to share on facebook there's an image attached to the link (as there should be as links without images will get hardly any clicks), but the image didn't work.  
> 
> The other thing is the text that is automatically put into the facebook post has a link to the faucet when it would be better to link to bitshares.org. Maybe that appears because the sharing is happening from the faucet.   It would be better to change it if possible as sharing a link to the faucet is pointless.
> 
> The text that is automatically put in the twitter-share tweet doesn't have a link to bitshares.org either, I suggest that be added.

**Comment by valzav** [comment]
https://github.com/cassiopaia/labs.bitshares.org/issues/43

**Comment by valzav** [comment]
addressed in this commit https://github.com/BitShares/web_services/commit/f04b23035ded96e39c0211a020901fbfe4ee7dcb
